language: node_js
node_js: stable
before_install:
- npm i -g nsp && nsp check
deploy:
  provider: npm
  email: mrkenbrowning@hotmail.com
  api_key:
    secure: PDC+q6LrBv1s7HXsj5FBy52G7shXptLgJ+5YSn1Ue8NpiWxOMNHhDlboWi5IxFDxeK4tg5orqqHUy7MENdRdH7ccJwicnO42amZBFhV1Jl+2R2B200PaiY09tLqpYTWrzQyxfFslsOiKyT6zji6SSIkkMVEPgB43n4dj8Z9AWvLzSalvJY1pk5L0o4/LtL1B02SVPvsLTk+cBSuWAFjo2Rb0ra84HsnIQXWoqt5S2tBj6DuLXHZ4VUizdU4oW/VnxMOsjQPfqZBD9IvIe4im6LxGgOqLyTLTqMJa0VOoGGxEI3ODlyetebALQhMLxZkCAWK8bwJINXrQ33F1FDGP0FgQALWDFc76CuCZtq3mzEyQ6+Xp/6sSBkmxHPriHIw9fEk4q8uXm3/xrqDw24ETVgAFDVMWf70f81ClofVzA2TSBia76uDnc1uLljIHG+Xm67PAB3zIycbNwHgentDOCrD2o/anhKIjsBxJzuOM0MKbqU2ssYJgj2mT+MREuytknHlcwqnKktSR4tse5Fb/laVgjIqg4e+caFf5Vh0cLxqX1dVGJF9VaD6a/0o0Ajd+VlqG9TsHW3EmkJuVo0N8sauPJ2Uh1+yJrEWvRYyGll31f0sD40ZuZrJK+LED6mZG649i1G6SxSeXtm+sL6TZ8l3cD39NbsZkvvzpt4G9yx0=
  on:
    tags: true
    repo: gavacho/ecs-deploy
    branch: master
